Description: 1cPGSQL maintenance
Host: 192.168.0.29
SQLUserName: postgres
1cServiceName: srv1cv83
1cServiceDir: /home/usr1cv8/.1cv8/1C/1cv8/reg_1541
PGServiceName: postgresql
BackUp:
  Dir: /mnt/pg_arch/ARCH
Do:
  - BackUp-SQL
  # - Reindex-SQL
  # - Vacuum-SQL
  - BackUp-1cExtFiles
  - Reset-1cJournals
  # - Clean-1cCache
  - FSCheck
  # - Reboot
BackUp-SQL:
  Depth: 7 #Days
  KeepQuantity: 10 #Archives
  RestoreManualTmpt: RestSQLManl.tmpt 
  RestoreManualFile: README.MD
BackUp-Bases:
  - "GILV"
  # - "%ERP%"
  # - "%BUH%"
  # - "%UPP%"
  # - "%ZUP%"
  # - "%ARCH%"
  #- "%KA-%" 

BackUp-1cExtFiles:
  # Dir: /mnt/pg_arch/ARCH
  1cExtFilesDir: /mnt/1cdata
  Depth: 60 #Days
  RestoreManualTmpt: RestFilesManl.tmpt 
  RestoreManualFile: README.MD

Reset-1cJournals:
  LogDirName: 1Cv8Log
  LogArchDirName: 1cLogs
  LogDepth: 90        #Days
  LogSizeMax: 1000    #MB
  KeepDepth: 365      #Days
  KeepSizeMax: 6000   #MB
  WaitAfter: 30       #sec

FSCheck:
  DiskSpaceUsageWarn: 75 #%
  DiskSpaceUsageErr: 90 #%

Reboot:
  TimeOut: 2  #min

log:
  file: "/opt/serv/serv.log"
  con: true 
  telegram:
    token:
    channel_id:

       

