Description: 1cPGSQL maintenance
Host: 192.168.0.29
SQLUserName: postgres     # Имя пользователя Postgresql
1cServiceName: srv1cv83   # Имя сервиса 1с
PGServiceName: postgresql
1cServiceDir: /home/usr1cv8/.1cv8/1C/1cv8/reg_1541  # Каталог где сервер хранит информации по базам
BackUp:                   
  Dir: /mnt/pg_arch/ARCH  # Раздел для архивов
Do:
  - BackUp-SQL            # Реализованные в программе таски
  # - Reindex-SQL           # Не трудно понять их смысл, подробней в 1cPSQLServ.py
  # - Vacuum-SQL
  - BackUp-1cExtFiles
  - Reset-1cJournals      # Удаляем в архив журналы 1c...
  - Clean-1cCache         # Удаляем кеш 1с сервера  (/snccntx*/*.dat)
  - FSCheck
  # - Reboot
BackUp-SQL:                           # По имени задач выше, параметры задач
  Depth: 7                            # Days - Хранить архивы баз X дней
  KeepQuantity: 10                    # Archives - Хранить минимум Х архивов (не трогать при удалении устаревших по настройке выше)
  RestoreManualTmpt: RestSQLManl.tmpt # Шаблон для инструкций 
  RestoreManualFile: README.MD        # Имя файла инструкций (ляжет в каталог с архивом базы, содержит описание и команды для восстановления)
  Bases:                         
    - "GILV"                          # Какие базы архивировать в Раздел для архивов
    # - "%ERP%"                       # Aрхивы SQL лягут в папку с именем базы в виде каталога с шифром даты-времени-версии_архива.
    # - "%BUH%"                         
    # - "%UPP%"
    # - "%ZUP%"
    - "%KA-%"  
BackUp-1cExtFiles:
  1cExtFilesDir: /mnt/1cdata          # Внешние файлы 1с. Каталоги с именами как у баз. Т.е. если база имеет имя ERP-A, то и прикрепленные файлы должны лежать в /mnt/1cdata/ERP-A.
  Depth: 60 #Days                     # Глубина хранения изменений
  RestoreManualTmpt: RestFilesManl.tmpt # Шаблон для инструкций 
  RestoreManualFile: README.MD          # Имя файла инструкций (ляжет в каталог с архивом базы, содержит описание и команды для восстановления)
  Bases:                         
    #- "GILV"                            # Внешние файлы каких баз архивировать
    - "%KA-%"                    
Reset-1cJournals:                     # Удаляем в архив журналы...
  LogDirName: 1Cv8Log                 # Логи 1с перенесутся в папку с именем базы в виде каталога LogArchDirName, как сжатый файл с шифром даты-времени.
  LogArchDirName: 1cLogs              # Имя каталога для архивов журналов 1с в каталоге архивов базы
  LogDepth: 90        #Days           # Если дата каталога LogDirName станет старее LogDepth, журнал удалится в архив. 
  LogSizeMax: 1000    #MB             # Если размер каталога LogDirName станет больше LogSizeMax, журнал удалится в архив. 
  KeepDepth: 365      #Days           # Хранить архивы X дней
  KeepSizeMax: 6000   #MB             # Не больше такого размера
  WaitAfter: 15       #sec            # Пауза после 

FSCheck:
  DiskSpaceUsageWarn: 60 #%           # Для одноименной задачи, порог предупреждения заполнения томов.
  DiskSpaceUsageErr: 90 #%            # Для одноименной задачи, порог критического заполнения томов.

Reboot:
  TimeOut: 2  #min                    # Задержка перезагрузки для успешного завершения скрипта 

log:
  file: "/opt/serv/serv.log"          # Куда логи пишем
  con: true                           # Вывод в консоль
  telegram:
    token:
    channel_id:

       

